server:
  port: 9030

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1/bangbang?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: redisson-serial